import {
  Bell,
  LayoutDashboard,
  MessageSquareText,
  Plus,
  Wifi,
} from "lucide-react";
import {
  aboutIcon as AboutIcon,
  educationIcon as EducationIcon,
  galleryIcon as GalleryIcon,
  complimentaryIcon as ComplimentaryIcon,
  slidericon as SliderIcon,
  articleIcon as ArticleIcon,
  testimonalsIcon as TestimonialsIcon,
  bookingIcon as BookingIcon,
  pricefeedbackIcon as PriceFeedbackIcon,
  AllEstimateSection,
  serviceIcon as ServiceIcon,
} from "../components/ui/icons";

// Navbar links
export const navLinks = [
  {
    name: "Dashboard",
    path: "/dashboard",
    icon: <Wifi className="w-5 h-5" />,
  },
  {
    name: "Paid Details",
    path: "/paid-details",
    icon: <MessageSquareText className="w-5 h-5" />,
  },
  {
    name: "Create & Send",
    path: "/create-send",
    icon: <Bell className="w-5 h-5" />,
  },
];

// Sidebar links
export const sidebarLinks = [
  {
    path: "/create-estimate",
    label: "Create Estimate",
    icon: <Plus className="w-4 h-4" />,
  },
  {
    path: "/dashboard",
    label: "Dashboard",
    icon: <LayoutDashboard className="w-5 h-5" />,
  },
  {
    path: "/content/sliders",
    label: "Content Management",
    icon: <ArticleIcon className="w-5 h-5" />,
    children: [
      {
        path: "/content/sliders",
        label: "Slider Section",
        icon: <SliderIcon />,
      },
      {
        path: "/content/articles",
        label: "Articles Section",
        icon: <ArticleIcon />,
      },
      {
        path: "/content/testimonials",
        label: "Client Testimonials",
        icon: <TestimonialsIcon />,
      },
      {
        path: "/content/complementary-services",
        label: "Complimentary Services",
        icon: <ComplimentaryIcon />,
      },
    ],
  },
  {
    path: "/bookings",
    label: "Bookings",
    icon: <BookingIcon className="w-5 h-5" />,
  },
  {
    path: "/all-estimates",
    label: "All Estimates",
    icon: <AllEstimateSection className="w-5 h-5" />,
  },
  {
    path: "/price-feedback",
    label: "Price Feedback",
    icon: <PriceFeedbackIcon className="w-5 h-5" />,
  },
  {
    path: "/about",
    label: "About Section",
    icon: <AboutIcon className="w-5 h-5" />,
  },
  {
    path: "/education",
    label: "Education Section",
    icon: <EducationIcon className="w-5 h-5" />,
  },
  {
    path: "/gallery",
    label: "Gallery Section",
    icon: <GalleryIcon className="w-5 h-5" />,
  },
  {
    path: "/query",
    label: "Query",
    icon: <ArticleIcon className="w-5 h-5" />,
  },
  {
    path: "/services",
    label: "Service Section",
    icon: <ServiceIcon className="w-5 h-5" />,
  },
];
// Professionals
export const professionals = [
  {
    id: 1,
    name: "James Robert",
    email: "jamesrobert@gmail.com",
    phone: "+1209876534",
    location: "Montreal, Quebec",
    avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    status: "Sent",
    bidAmount: "$3466",
    bidAt: "11 Aug 2025 at 06:03:12",
  },
  {
    id: 2,
    name: "James Robert",
    email: "jamesrobert@gmail.com",
    phone: "+1209876534",
    location: "Montreal, Quebec",
    avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    status: "Sent",
    bidAmount: "$3466",
    bidAt: "11 Aug 2025 at 06:03:12",
  },
  {
    id: 3,
    name: "James Robert",
    email: "jamesrobert@gmail.com",
    phone: "+1209876534",
    location: "Montreal, Quebec",
    avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    status: "Viewed",
    bidAmount: "$3466",
    bidAt: "11 Aug 2025 at 06:03:12",
  },
  {
    id: 4,
    name: "James Robert",
    email: "jamesrobert@gmail.com",
    phone: "+1209876534",
    location: "Montreal, Quebec",
    avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    status: "Added",
    bidAmount: "$3466",
    bidAt: "11 Aug 2025 at 06:03:12",
  },
];

export const estimatesData = [
  {
    id: 1,
    jobId: "#JOB-394413",
    title: "Home Painting service...",
    customer: {
      name: "James Robert",
      phone: "+11209876534",
      avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    },
    address: "Highway 407, Vaughan, Ontario, Canada...",
    price: "$21345",
    services: "Appliance Install",
    moreServices: "+2 more services",
    assignStatus: "2/3",
    status: "Requested",
    statusColor: "bg-orange-100 text-orange-600",
  },
  {
    id: 2,
    jobId: "#JOB-394413",
    title: "Home Painting service...",
    customer: {
      name: "James Robert",
      phone: "+11209876534",
      avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    },
    address: "Highway 407, Vaughan, Ontario, Canada...",
    price: "$21345",
    services: "Appliance Install",
    moreServices: "+2 more services",
    assignStatus: "2/3",
    status: "Paid",
    statusColor: "bg-green-100 text-green-600",
  },
  {
    id: 3,
    jobId: "#JOB-394413",
    title: "Home Painting service...",
    customer: {
      name: "James Robert",
      phone: "+11209876534",
      avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    },
    address: "Highway 407, Vaughan, Ontario, Canada...",
    price: "$21345",
    services: "Appliance Install",
    moreServices: "+2 more services",
    assignStatus: "2/3",
    status: "Paid",
    statusColor: "bg-green-100 text-green-600",
  },
  {
    id: 4,
    jobId: "#JOB-394413",
    title: "Home Painting service...",
    customer: {
      name: "James Robert",
      phone: "+11209876534",
      avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    },
    address: "Highway 407, Vaughan, Ontario, Canada...",
    price: "$21345",
    services: "Appliance Install",
    moreServices: "+2 more services",
    assignStatus: "2/3",
    status: "Paid",
    statusColor: "bg-green-100 text-green-600",
  },
  {
    id: 5,
    jobId: "#JOB-394413",
    title: "Home Painting service...",
    customer: {
      name: "James Robert",
      phone: "+11209876534",
      avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    },
    address: "Highway 407, Vaughan, Ontario, Canada...",
    price: "$21345",
    services: "Appliance Install",
    moreServices: "+2 more services",
    assignStatus: "2/3",
    status: "Paid",
    statusColor: "bg-green-100 text-green-600",
  },
];

export const tabs = [
  { id: "all", label: "All Estimates", count: 58 },
  { id: "paid", label: "Paid", count: 12 },
  { id: "requested", label: "Requested", count: 23 },
  { id: "viewed", label: "Viewed", count: 10 },
  { id: "not-initiated", label: "Not Initiated", count: 2 },
];

export const servicesData = [
  {
    id: 1,
    serviceName: "Appliance Install",
    regAmount: "$32",
    totalCost: "$4800",
    paymentStatus: "Requested",
    paymentStatusColor: "bg-orange-100 text-orange-600",
    jobAssignStatus: "Not Initiated",
    jobAssignStatusColor: "bg-red-100 text-red-600",
  },
  {
    id: 2,
    serviceName: "Appliance Repair",
    regAmount: "$30",
    totalCost: "$5500",
    paymentStatus: "Paid",
    paymentStatusColor: "bg-green-100 text-green-600",
    jobAssignStatus: "Link Created",
    jobAssignStatusColor: "bg-blue-100 text-blue-600",
  },
  {
    id: 3,
    serviceName: "Flooring and Tile Services",
    regAmount: "$50",
    totalCost: "$5500",
    paymentStatus: "Paid",
    paymentStatusColor: "bg-green-100 text-green-600",
    jobAssignStatus: "Bidding Ongoing",
    jobAssignStatusColor: "bg-blue-100 text-blue-600",
  },
  {
    id: 4,
    serviceName: "Flooring and Tile Services",
    regAmount: "$50",
    totalCost: "$5500",
    paymentStatus: "Paid",
    paymentStatusColor: "bg-green-100 text-green-600",
    jobAssignStatus: "Assigned",
    jobAssignStatusColor: "bg-purple-100 text-purple-600",
  },
  {
    id: 5,
    serviceName: "Flooring and Tile Services",
    regAmount: "$50",
    totalCost: "$5500",
    paymentStatus: "Paid",
    paymentStatusColor: "bg-green-100 text-green-600",
    jobAssignStatus: "Work Ongoing",
    jobAssignStatusColor: "bg-yellow-100 text-yellow-600",
  },
  {
    id: 6,
    serviceName: "Flooring and Tile Services",
    regAmount: "$50",
    totalCost: "$5500",
    paymentStatus: "Paid",
    paymentStatusColor: "bg-green-100 text-green-600",
    jobAssignStatus: "Completed",
    jobAssignStatusColor: "bg-green-100 text-green-600",
  },
];

export const invoiceData = [
  {
    srNo: 1,
    amount: "$1200",
    description: "Registered Amount",
    status: "Completed",
    method: "UPI",
    date: "2025-09-20",
  },
  {
    srNo: 2,
    amount: "$2100",
    description: "Registered Amount",
    status: "Pending",
    method: "-",
    date: "2025-09-25",
  },
  {
    srNo: 3,
    amount: "$750",
    description: "Registered Amount",
    status: "Not Initiated",
    method: "-",
    date: "2025-10-05",
  },
];
